### ISSUE TITLE
make the global seed no work

### ISSUE THREAD

**Issue by xueqing0622** [vivax3794/ComfyUI-Sub-Nodes#12]
make this two GlobalSeed no work with randomize
https://github.com/ltdrdata/ComfyUI-Inspire-Pack
https://github.com/yolain/ComfyUI-Easy-Use
![image](https://github.com/vivax3794/ComfyUI-Sub-Nodes/assets/114840118/7631a049-e2ff-4fbf-8fde-2971ad65270a)

**Comment by MatissesProjects** [comment]
making a random in the top layer of the graphs and passing it in works well for this

**Comment by xueqing0622** [comment]
other random seed is ok, just no work these two global seed nodes,

**Comment by vivax3794** [comment]
These should both work if you rename the input to "seed" exactly (which is now possible due to a recent pushed update)
