### ISSUE TITLE
Suggestions for functionality: 

### ISSUE THREAD

**Issue by 807502278** [vivax3794/ComfyUI-Sub-Nodes#15]
Suggestion 1: Add an input to the VIV_Subgraph_Inputs node to specify a default value (this input can be optionally connected when using VIV_Subgraph), similar to UnrealEngine. 
Suggestion 2: Add a string value to the VIV_Subgraph_Inputs node for specifying the input name. 
Suggestion 3: Introduce a node of the VIV_Subgraph_Inputs_value type, and when using VIV_Subgraph, make the inputs of this node numeric values instead of connection points(unimportance).

other：NaN bug？
![image](https://github.com/user-attachments/assets/56ffb426-5d16-4929-a18a-2463d2d47c8f)

**Comment by MatissesProjects** [comment]
you can do the defaults
![Screenshot 2024-07-17 080822](https://github.com/user-attachments/assets/9018fce1-743f-4e96-a38b-78bd42427e4c)
the first screenshot is the normal naming if you connect the sockets to the needed items, and the second one indicates that these are possible defaults
![Screenshot 2024-07-17 080929](https://github.com/user-attachments/assets/38a2caca-1ba3-43dd-a495-ca9514598a16)
one problem with this is that you might end up with items that need to be defined as groups that dont, like in the case shown here you would need the whole model set, but this allows you to do that.
![image](https://github.com/user-attachments/assets/61743c92-77ff-4bd6-9b70-95d37aee7b96)
Also I believe the latest version also contains the ability to add strings directly into the graph top.

+1 on that nan bug being a bit strange, but that is likely on the list of things to be cleaned up for ease of life

**Comment by 807502278** [comment]
Thank you, this vive_default is very useful!
