### ISSUE TITLE
Doesn't work when using Docker

### ISSUE THREAD

**Issue by cian0** [vivax3794/ComfyUI-Sub-Nodes#16]
I added subnodes folder from within the docker container, it was able to find the workflow but it won't change appropriately (tried restarting etc)
![image](https://github.com/user-attachments/assets/b3ec1b7f-d436-476b-999b-58ad450d774b)

**Comment by cian0** [comment]
Here's how the test_subnode_workflow looks like:

![image](https://github.com/user-attachments/assets/45c30127-621c-4d1a-9752-5abfb1a465bd)

**Comment by vivax3794** [comment]
I personally use docker to run comfy, it's the setup I used to develop the nodes, can you share your docker file and the compose file/command you use to run it so I can see what the issue might be?

**Comment by vivax3794** [comment]
Closing due to lack of information.
