### ISSUE TITLE
Input widgets are pointless

### ISSUE THREAD

**Issue by SirVeggie** [vivax3794/ComfyUI-Sub-Nodes#17]
Currently the input widgets are quite horrible (sorry). They don't respect the input type correctly, the names are too verbose, input slots and widgets are duplicated, and they take unnecessary space (since they're pretty unusable in the first place).
I would rather they wouldn't exist at all, at least until they work correctly.

Another but a very minor point would be that after choosing a subgraph from the menu, the workflow widget would hide. After all you don't need to interact with it anymore after choosing the workflow, since you wouldn't be changing it anyway. This way the node would look cleaner, assuming the other widgets are removed as well. I like as little unnecessary visual information on things as possible, but as I said this one is just a minor gripe.

**Comment by vivax3794** [comment]
I'm the newest versions I majorly improved the widgets, they are no longer duplicated with the slots, and they respect the default value of whatever they are connected to. You can now also rename the input and outputs

**Comment by SirVeggie** [comment]
sweet!
