### ISSUE TITLE
WARNING: Error parsing dependencies of torchsde

### ISSUE THREAD

**Issue by xueqing0622** [vivax3794/ComfyUI-Sub-Nodes#4]
install  requirements.txt  rich, show
Requirement already satisfied: rich in f:\comfyui\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (13.5.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in f:\comfyui\python_embeded\lib\site-packages (from rich->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in f:\comfyui\python_embeded\lib\site-packages (from rich->-r requirements.txt (line 1)) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in f:\comfyui\python_embeded\lib\site-packages (from markdown-it-py>=2.2.0->rich->-r requirements.txt (line 1)) (0.1.1)
WARNING: Error parsing dependencies of torchsde: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"

**Comment by vivax3794** [comment]
this is a issue with `torchsde` and not related to this project.
