### ISSUE TITLE
how about add widget and input number to subgraph

### ISSUE THREAD

**Issue by xueqing0622** [vivax3794/ComfyUI-Sub-Nodes#6]
how about add widget and input number to subgraph

**Comment by vivax3794** [comment]
Not quite sure what you are asking about? can you explain with a example?

**Comment by xueqing0622** [comment]
It is support now, thx
I mean this, 
![image](https://github.com/user-attachments/assets/e892334b-1b48-4424-88c8-25c9329653da)
